<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
        DB::table('truong')->insert([
            ['ten_truong'=>"Trường Tiểu Học Bách Khoa",'level'=>1,'dia_chi'=>"Số 11,Lê thanh nghị ,Hai bà trưng,Hà Nội"],
            ['ten_truong'=>"Trường trung học cơ sở Bách Khoa",'level'=>2,'dia_chi'=>"Số 12,Lê thanh nghị ,Hai bà trưng,Hà Nội"],
            ['ten_truong'=>"Trường trung học phổ thông Bách Khoa",'level'=>2,'dia_chi'=>"Số 112,Lê thanh nghị ,Hai bà trưng,Hà Nội"],
        ]);
        DB::table('nam_hoc')->insert([
            ['nam_hoc'=>'2012-2013'],
            ['nam_hoc'=>'2013-2014'],
            ['nam_hoc'=>'2014-2015'],
            ['nam_hoc'=>'2014-2015'],
            ['nam_hoc'=>'2015-2016'],
            ['nam_hoc'=>'2016-2017'],
            ['nam_hoc'=>'2017-2018'],
            ['nam_hoc'=>'2018-2019'],
            ['nam_hoc'=>'2019-2020'],
        ]);
        DB::table('mon_hoc')->insert([
            ['ten_mon'=>'Toán'],
            ['ten_mon'=>'Văn'],
            ['ten_mon'=>'Tiếng Anh'],
            ['ten_mon'=>'Vật Lý'],
            ['ten_mon'=>'Hóa Học'],
            ['ten_mon'=>'Sinh Học'],
            ['ten_mon'=>'Lịch Sử'],
            ['ten_mon'=>'Địa Lý'],
            ['ten_mon'=>'Thể Dục'],
            ['ten_mon'=>'Giáo Dục Công Dân'],
            ['ten_mon'=>'Công Nghệ'],
            ['ten_mon'=>'Mỹ Thuật'],
            ['ten_mon'=>'Âm Nhạc'],
            ['ten_mon'=>'Tiếng việt'],
            ['ten_mon'=>'TNXH'],
            ['ten_mon'=>'Tin học'],
            ['ten_mon'=>'Đạo đức'],
            ['ten_mon'=>'Thủ công'],
        ]);
        DB::table('hoc_ki')->insert([
            ['hoc_ki'=>1,'id_namhoc'=>1],
            ['hoc_ki'=>2,'id_namhoc'=>1],
            ['hoc_ki'=>1,'id_namhoc'=>2],
            ['hoc_ki'=>2,'id_namhoc'=>2],
            ['hoc_ki'=>1,'id_namhoc'=>3],
            ['hoc_ki'=>2,'id_namhoc'=>3],
            ['hoc_ki'=>1,'id_namhoc'=>4],
            ['hoc_ki'=>2,'id_namhoc'=>4],
            ['hoc_ki'=>1,'id_namhoc'=>5],
            ['hoc_ki'=>2,'id_namhoc'=>5],
            ['hoc_ki'=>1,'id_namhoc'=>6],
            ['hoc_ki'=>2,'id_namhoc'=>6],
            ['hoc_ki'=>1,'id_namhoc'=>7],
            ['hoc_ki'=>2,'id_namhoc'=>7],
            ['hoc_ki'=>1,'id_namhoc'=>8],
            ['hoc_ki'=>2,'id_namhoc'=>8],
            ['hoc_ki'=>1,'id_namhoc'=>9],
        ]);
        DB::table('lop_hoc')->insert([
            ['id_truong'=>1,'ten_lop'=>"1A"],
            ['id_truong'=>1,'ten_lop'=>"1B"],
            ['id_truong'=>1,'ten_lop'=>"1C"],
            ['id_truong'=>1,'ten_lop'=>"1D"],
            ['id_truong'=>1,'ten_lop'=>"2A"],
            ['id_truong'=>1,'ten_lop'=>"2B"],
            ['id_truong'=>1,'ten_lop'=>"2C"],
            ['id_truong'=>1,'ten_lop'=>"2D"],
            ['id_truong'=>1,'ten_lop'=>"3A"],
            ['id_truong'=>1,'ten_lop'=>"3B"],
            ['id_truong'=>1,'ten_lop'=>"3C"],
            ['id_truong'=>1,'ten_lop'=>"3D"],
            ['id_truong'=>1,'ten_lop'=>"4A"],
            ['id_truong'=>1,'ten_lop'=>"4B"],
            ['id_truong'=>1,'ten_lop'=>"4C"],
            ['id_truong'=>1,'ten_lop'=>"4D"],
            ['id_truong'=>1,'ten_lop'=>"5A"],
            ['id_truong'=>1,'ten_lop'=>"5B"],
            ['id_truong'=>1,'ten_lop'=>"5C"],
            ['id_truong'=>1,'ten_lop'=>"5D"],
            ['id_truong'=>2,'ten_lop'=>"6A"],
            ['id_truong'=>2,'ten_lop'=>"6B"],
            ['id_truong'=>2,'ten_lop'=>"6C"],
            ['id_truong'=>2,'ten_lop'=>"6D"],
            ['id_truong'=>2,'ten_lop'=>"7A"],
            ['id_truong'=>2,'ten_lop'=>"7B"],
            ['id_truong'=>2,'ten_lop'=>"7C"],
            ['id_truong'=>2,'ten_lop'=>"7D"],
            ['id_truong'=>2,'ten_lop'=>"8A"],
            ['id_truong'=>2,'ten_lop'=>"8B"],
            ['id_truong'=>2,'ten_lop'=>"8C"],
            ['id_truong'=>2,'ten_lop'=>"8D"],
            ['id_truong'=>2,'ten_lop'=>"9A"],
            ['id_truong'=>2,'ten_lop'=>"9B"],
            ['id_truong'=>2,'ten_lop'=>"9C"],
            ['id_truong'=>2,'ten_lop'=>"9D"],
            ['id_truong'=>3,'ten_lop'=>"10A"],
            ['id_truong'=>3,'ten_lop'=>"10B"],
            ['id_truong'=>3,'ten_lop'=>"10C"],
            ['id_truong'=>3,'ten_lop'=>"10D"],
            ['id_truong'=>3,'ten_lop'=>"11A"],
            ['id_truong'=>3,'ten_lop'=>"11B"],
            ['id_truong'=>3,'ten_lop'=>"11C"],
            ['id_truong'=>3,'ten_lop'=>"11D"],
            ['id_truong'=>3,'ten_lop'=>"12A"],
            ['id_truong'=>3,'ten_lop'=>"12B"],
            ['id_truong'=>3,'ten_lop'=>"12C"],
            ['id_truong'=>3,'ten_lop'=>"12D"],

        ]);
        DB::table('users')->insert([
            ['name'=>"root",'password'=>bcrypt('matkhau'),'email' => 'duongminhquang98'.'@gmail.com','level'=>0],
            ['name'=>"tranvien98@gmail.com",'password'=>bcrypt('matkhau'),'email' => 'tranvien98'.'@gmail.com','level'=>1],
            ['name'=>"VT3",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>2],
            ['name'=>"GV4",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"HS5",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS6",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS7",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS8",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS9",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"GV10",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV11",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"HS12",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS13",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS14",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS15",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS16",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"VT17",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>2],
            ['name'=>"VT18",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>2],
            ['name'=>"VT19",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>2],
            ['name'=>"GV20",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV21",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV22",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV23",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV24",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV25",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV26",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV27",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV28",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV29",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV30",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV31",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV32",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"HS33",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS34",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS35",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS36",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS37",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS38",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS39",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS40",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"GV41",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"HS42",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS43",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS44",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS45",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS46",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS47",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS48",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"HS49",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>4],
            ['name'=>"GV50",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV51",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV52",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV53",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"GV54",'password'=>bcrypt('matkhau'),'email' => str_random(10).'@gmail.com','level'=>3],
            ['name'=>"tranvan98@gmail.com",'password'=>bcrypt('matkhau'),'email' => 'tranvan98'.'@gmail.com','level'=>1],


        ]);
        DB::table('van_thu')->insert([
            ['id_truong'=>2,'id_taikhoan'=>3,'ho_ten'=>"Nguyen Thi  A",'gioi_tinh'=>'Nữ','so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','dia_chi'=>'Hai ba trung'],
            ['id_truong'=>1,'id_taikhoan'=>17,'ho_ten'=>"Nguyen Thi  B",'gioi_tinh'=>'Nữ','so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','dia_chi'=>'Hai ba trung'],
            ['id_truong'=>2,'id_taikhoan'=>18,'ho_ten'=>"Nguyen Thi  C",'gioi_tinh'=>'Nữ','so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','dia_chi'=>'Hai ba trung'],
            ['id_truong'=>3,'id_taikhoan'=>19,'ho_ten'=>"Nguyen Thi  D",'gioi_tinh'=>'Nữ','so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','dia_chi'=>'Hai ba trung'],
        ]);
        DB::table('admin')->insert([
            ['id_taikhoan'=>1,'ho_ten'=>"Dương Minh Quang",'gioi_tinh'=>'Nam','so_dien_thoai'=>'0377106571','email'=>'duongminhquang98'.'@gmail.com','dia_chi'=>'Bắc Giang'],
            ['id_taikhoan'=>2,'ho_ten'=>"Trần Văn Viên",'gioi_tinh'=>'Nam','so_dien_thoai'=>'0377106557','email'=>'tranvien98@gmail.com','dia_chi'=>'Bắc Giang'],
            ['id_taikhoan'=>55,'ho_ten'=>"Nguyễn Văn Văn",'gioi_tinh'=>'Nam','so_dien_thoai'=>'0377106557','email'=>'tranvan98@gmail.com','dia_chi'=>'Bắc Giang'],

        ]);
        DB::table('thong_bao')->insert([
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>3,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>3,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>3,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>3,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>3,'id_truong'=>2],
            ['tieu_de'=>"Lịch thi học kỳ 2018-2019",'tom_tat'=>"Thông báo lịch thi cuối 2 năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>3,'id_truong'=>2],
        ]);
        DB::table('danh_sach_gv')->insert([
            ['id_truong'=>1,'id_hocki'=>1],
            ['id_truong'=>1,'id_hocki'=>2],
            ['id_truong'=>1,'id_hocki'=>3],
            ['id_truong'=>1,'id_hocki'=>4],
            ['id_truong'=>1,'id_hocki'=>5],
            ['id_truong'=>1,'id_hocki'=>6],
            ['id_truong'=>1,'id_hocki'=>7],
            ['id_truong'=>1,'id_hocki'=>8],
            ['id_truong'=>1,'id_hocki'=>9],
            ['id_truong'=>1,'id_hocki'=>10],
            ['id_truong'=>1,'id_hocki'=>11],
            ['id_truong'=>1,'id_hocki'=>12],
            ['id_truong'=>1,'id_hocki'=>13],
            ['id_truong'=>1,'id_hocki'=>14],
            ['id_truong'=>1,'id_hocki'=>15],
            ['id_truong'=>1,'id_hocki'=>16],
            ['id_truong'=>1,'id_hocki'=>17],
            ['id_truong'=>2,'id_hocki'=>1],
            ['id_truong'=>2,'id_hocki'=>2],
            ['id_truong'=>2,'id_hocki'=>3],
            ['id_truong'=>2,'id_hocki'=>4],
            ['id_truong'=>2,'id_hocki'=>5],
            ['id_truong'=>2,'id_hocki'=>6],
            ['id_truong'=>2,'id_hocki'=>7],
            ['id_truong'=>2,'id_hocki'=>8],
            ['id_truong'=>2,'id_hocki'=>9],
            ['id_truong'=>2,'id_hocki'=>10],
            ['id_truong'=>2,'id_hocki'=>11],
            ['id_truong'=>2,'id_hocki'=>12],
            ['id_truong'=>2,'id_hocki'=>13],
            ['id_truong'=>2,'id_hocki'=>14],
            ['id_truong'=>2,'id_hocki'=>15],
            ['id_truong'=>2,'id_hocki'=>16],
            ['id_truong'=>2,'id_hocki'=>17],

        ]);
        DB::table('giao_vien')->insert([
            ['id_danh_sach_gv'=>13,'id_mon'=>1,'id_taikhoan'=>4,'ho_ten'=>"Le Van A",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>'Truong bo mon'],
            ['id_danh_sach_gv'=>14,'id_mon'=>14,'id_taikhoan'=>4,'ho_ten'=>"Le Van B",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>32,'id_mon'=>2,'id_taikhoan'=>10,'ho_ten'=>"Trần Thị Bính",'gioi_tinh'=>"Nữ",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>33,'id_mon'=>4,'id_taikhoan'=>10,'ho_ten'=>"Trần Thị Bị",'gioi_tinh'=>"Nữ",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>1,'id_taikhoan'=>11,'ho_ten'=>"Dung Van C",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>2,'id_taikhoan'=>20,'ho_ten'=>"Dung Van D",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>3,'id_taikhoan'=>21,'ho_ten'=>"Dung Van E",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>4,'id_taikhoan'=>22,'ho_ten'=>"Dung Van F",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>5,'id_taikhoan'=>23,'ho_ten'=>"Dung Van G",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>6,'id_taikhoan'=>24,'ho_ten'=>"Dung Van H",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>7,'id_taikhoan'=>25,'ho_ten'=>"Dung Van I",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>1,'id_taikhoan'=>4,'ho_ten'=>"Le Van B",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>9,'id_taikhoan'=>28,'ho_ten'=>"Le Van B",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>12,'id_taikhoan'=>29,'ho_ten'=>"Le Van D",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>13,'id_taikhoan'=>27,'ho_ten'=>"Le Van E",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>15,'id_taikhoan'=>27,'ho_ten'=>"Le Van E",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>16,'id_taikhoan'=>31,'ho_ten'=>"Tran Thu T",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>17,'id_taikhoan'=>28,'ho_ten'=>"Le Van B",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>14,'id_mon'=>18,'id_taikhoan'=>30,'ho_ten'=>"Le Mai Y",'gioi_tinh'=>"Nữ",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>1,'id_taikhoan'=>41,'ho_ten'=>"Trần Hữu Nghĩa",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>14,'id_taikhoan'=>41,'ho_ten'=>"Trần Hữu Nghĩa",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>11,'id_taikhoan'=>41,'ho_ten'=>"Trần Hữu Nghĩa",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>15,'id_taikhoan'=>41,'ho_ten'=>"Trần Hữu Nghĩa",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>17,'id_taikhoan'=>41,'ho_ten'=>"Trần Hữu Nghĩa",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>18,'id_taikhoan'=>41,'ho_ten'=>"Trần Hữu Nghĩa",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>16,'id_taikhoan'=>31,'ho_ten'=>"Tran Thu Thuy",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>17,'id_mon'=>3,'id_taikhoan'=>27,'ho_ten'=>"Le Van E",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>1,'id_taikhoan'=>50,'ho_ten'=>"Hoàng Văn  AA",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>2,'id_taikhoan'=>51,'ho_ten'=>"Hoàng Văn  BB",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>2,'id_taikhoan'=>52,'ho_ten'=>"Hoàng Văn  CC",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>4,'id_taikhoan'=>53,'ho_ten'=>"Hoàng Văn  DD",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],
            ['id_danh_sach_gv'=>34,'id_mon'=>5,'id_taikhoan'=>54,'ho_ten'=>"Hoàng Văn  EE",'gioi_tinh'=>"Nam",'so_dien_thoai'=>'0377106557','email'=>str_random(10).'@gmail.com','ngay_sinh'=>"01/02/1988",'dia_chi'=>'Hai ba trung,Ha Noi','chuc_vu'=>''],

        ]);

        DB::table('lop_day')->insert([
            ['id_giaovien'=>6,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>6,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>6,'id_lop'=>29,'id_hocki'=>17],
            ['id_giaovien'=>6,'id_lop'=>31,'id_hocki'=>17],
            ['id_giaovien'=>6,'id_lop'=>32,'id_hocki'=>17],
            ['id_giaovien'=>20,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>21,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>21,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>23,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>24,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>25,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>26,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>27,'id_lop'=>17,'id_hocki'=>17],
            ['id_giaovien'=>2,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>12,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>13,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>14,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>15,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>16,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>17,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>18,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>5,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>7,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>8,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>9,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>10,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>11,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>28,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>29,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>30,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>31,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>32,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>10,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>11,'id_lop'=>26,'id_hocki'=>17],

        ]);

        DB::table('danh_sach_hs')->insert([
            ['id_giaovien'=>1,'id_lop'=>17,'id_hocki'=>13],
            ['id_giaovien'=>2,'id_lop'=>17,'id_hocki'=>14],
            ['id_giaovien'=>3,'id_lop'=>21,'id_hocki'=>15],
            ['id_giaovien'=>4,'id_lop'=>21,'id_hocki'=>16],
            ['id_giaovien'=>5,'id_lop'=>25,'id_hocki'=>17],
            ['id_giaovien'=>6,'id_lop'=>26,'id_hocki'=>17],
            ['id_giaovien'=>7,'id_lop'=>27,'id_hocki'=>17],
            ['id_giaovien'=>8,'id_lop'=>28,'id_hocki'=>17],
            ['id_giaovien'=>9,'id_lop'=>29,'id_hocki'=>17],
            ['id_giaovien'=>10,'id_lop'=>30,'id_hocki'=>17],
            ['id_giaovien'=>11,'id_lop'=>31,'id_hocki'=>17],
            ['id_giaovien'=>20,'id_lop'=>17,'id_hocki'=>17],


        ]);
        DB::table('hoc_sinh')->insert([
            ['id_danh_sach_hs'=>1,'id_taikhoan'=>8,'ho_ten'=>"Trần Văn C",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>1,'id_taikhoan'=>9,'ho_ten'=>"Dương Thị Tính",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>1,'id_taikhoan'=>5,'ho_ten'=>"Dương Ngọc Tú",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>1,'id_taikhoan'=>12,'ho_ten'=>"Trần Thị Tú",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'12/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>1,'id_taikhoan'=>13,'ho_ten'=>"Trần Thị Thanh",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'12/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>2,'id_taikhoan'=>8,'ho_ten'=>"Trần Văn C",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>2,'id_taikhoan'=>5,'ho_ten'=>"Dương Ngọc Tú",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>2,'id_taikhoan'=>9,'ho_ten'=>"Dương Thị Tính",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>2,'id_taikhoan'=>12,'ho_ten'=>"Trần Thị Tú",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'12/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>2,'id_taikhoan'=>13,'ho_ten'=>"Trần Thị Thanh",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'12/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>3,'id_taikhoan'=>6,'ho_ten'=>"Trần Văn A",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>3,'id_taikhoan'=>7,'ho_ten'=>"Trần Văn B",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>3,'id_taikhoan'=>8,'ho_ten'=>"Trần Văn C",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>3,'id_taikhoan'=>14,'ho_ten'=>"Trần Văn Thành",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>3,'id_taikhoan'=>5,'ho_ten'=>"Dương Ngọc Tú",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>4,'id_taikhoan'=>6,'ho_ten'=>"Trần Văn A",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>4,'id_taikhoan'=>7,'ho_ten'=>"Trần Văn B",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>4,'id_taikhoan'=>8,'ho_ten'=>"Trần Văn C",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>4,'id_taikhoan'=>5,'ho_ten'=>"Dương Ngọc Tú",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>4,'id_taikhoan'=>14,'ho_ten'=>"Trần Văn Thành",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>5,'id_taikhoan'=>6,'ho_ten'=>"Trần Thị A",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'12/05/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>5,'id_taikhoan'=>7,'ho_ten'=>"Trần Văn B",'gioi_tinh'=>"Nam",'ngay_sinh'=>'04/12/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>5,'id_taikhoan'=>8,'ho_ten'=>"Trần Văn C",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>5,'id_taikhoan'=>15,'ho_ten'=>"Trần Văn D",'gioi_tinh'=>"Nam",'ngay_sinh'=>'10/08/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>5,'id_taikhoan'=>5,'ho_ten'=>"Dương Ngọc Tú",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>33,'ho_ten'=>"Dương Van AA",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>34,'ho_ten'=>"Dương Van BB",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>35,'ho_ten'=>"Dương Van CC",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>36,'ho_ten'=>"Dương Van DD",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>37,'ho_ten'=>"Dương Van EE",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>38,'ho_ten'=>"Dương Van FF",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>39,'ho_ten'=>"Dương Van GG",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>6,'id_taikhoan'=>40,'ho_ten'=>"Dương Van HH",'gioi_tinh'=>"Nam",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>42,'ho_ten'=>"Trần Thị AB",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>43,'ho_ten'=>"Trần Thị BC",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>44,'ho_ten'=>"Trần Thị CD",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>45,'ho_ten'=>"Trần Thị DE",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>46,'ho_ten'=>"Trần Thị EG",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>47,'ho_ten'=>"Trần Thị GH",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>48,'ho_ten'=>"Trần Thị HI",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],
            ['id_danh_sach_hs'=>12,'id_taikhoan'=>49,'ho_ten'=>"Trần Thị IK",'gioi_tinh'=>"Nữ",'ngay_sinh'=>'15/04/2006','dia_chi'=>'Hai ba trung,Ha Noi'],

        ]);
        DB::table('bang_tong_ket')->insert([
            ['id_hocsinh'=>25,'hoc_luc'=>'Giỏi','diem_phay_cuoi'=>8.6,'hanh_kiem'=>'Tốt','nhan_xet'=>"Tính toán còn chậm, còn nhiều sai sót. Cần rèn nhiều về nhân, chia, giải toán có lời văn.Hoàn thành tốt nội dung môn học."],
            ['id_hocsinh'=>21,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>22,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>23,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>24,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>26,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>27,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>28,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>29,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>30,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>31,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>32,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>33,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>34,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>35,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>36,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>37,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>38,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>39,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>40,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],
            ['id_hocsinh'=>41,'hoc_luc'=>null,'diem_phay_cuoi'=>null,'hanh_kiem'=>null,'nhan_xet'=>null],

        ]);
        DB::table('danh_sach_bd')->insert([
            ['id_tongket'=>1,'id_hocki'=>17],
            ['id_tongket'=>2,'id_hocki'=>17],
            ['id_tongket'=>3,'id_hocki'=>17],
            ['id_tongket'=>4,'id_hocki'=>17],
            ['id_tongket'=>5,'id_hocki'=>17],
            ['id_tongket'=>6,'id_hocki'=>17],
            ['id_tongket'=>7,'id_hocki'=>17],
            ['id_tongket'=>8,'id_hocki'=>17],
            ['id_tongket'=>9,'id_hocki'=>17],
            ['id_tongket'=>10,'id_hocki'=>17],
            ['id_tongket'=>11,'id_hocki'=>17],
            ['id_tongket'=>12,'id_hocki'=>17],
            ['id_tongket'=>13,'id_hocki'=>17],
            ['id_tongket'=>14,'id_hocki'=>17],
            ['id_tongket'=>15,'id_hocki'=>17],
            ['id_tongket'=>16,'id_hocki'=>17],
            ['id_tongket'=>17,'id_hocki'=>17],
            ['id_tongket'=>18,'id_hocki'=>17],
            ['id_tongket'=>19,'id_hocki'=>17],
            ['id_tongket'=>20,'id_hocki'=>17],
            ['id_tongket'=>21,'id_hocki'=>17],

        ]);
        DB::table('bang_diem')->insert([
            ['id_danh_sach_bd'=>1,'id_giaovien'=>5,'id_mon'=>1],
            ['id_danh_sach_bd'=>1,'id_giaovien'=>6,'id_mon'=>2],
            ['id_danh_sach_bd'=>1,'id_giaovien'=>7,'id_mon'=>3],
            ['id_danh_sach_bd'=>1,'id_giaovien'=>8,'id_mon'=>4],
            ['id_danh_sach_bd'=>1,'id_giaovien'=>9,'id_mon'=>5],
            ['id_danh_sach_bd'=>1,'id_giaovien'=>10,'id_mon'=>6],
            ['id_danh_sach_bd'=>1,'id_giaovien'=>11,'id_mon'=>7],

        ]);
        DB::table('diem_phay')->insert([
            ['id_bangdiem'=>1,'diem'=>8.6],
            ['id_bangdiem'=>2,'diem'=>8.6],
            ['id_bangdiem'=>3,'diem'=>8.6],
            ['id_bangdiem'=>4,'diem'=>8.6],
            ['id_bangdiem'=>5,'diem'=>8.6],
            ['id_bangdiem'=>6,'diem'=>8.6],
            ['id_bangdiem'=>7,'diem'=>8.6],
        ]);
        DB::table('he_so1')->insert([
            ['id_bangdiem'=>1,'diem'=>9],
            ['id_bangdiem'=>1,'diem'=>8],
            ['id_bangdiem'=>1,'diem'=>7],
            ['id_bangdiem'=>2,'diem'=>9],
            ['id_bangdiem'=>2,'diem'=>8],
            ['id_bangdiem'=>2,'diem'=>7],
            ['id_bangdiem'=>3,'diem'=>9],
            ['id_bangdiem'=>3,'diem'=>8],
            ['id_bangdiem'=>3,'diem'=>7],
            ['id_bangdiem'=>4,'diem'=>9],
            ['id_bangdiem'=>4,'diem'=>8],
            ['id_bangdiem'=>4,'diem'=>7],
            ['id_bangdiem'=>5,'diem'=>9],
            ['id_bangdiem'=>5,'diem'=>8],
            ['id_bangdiem'=>5,'diem'=>7],
            ['id_bangdiem'=>6,'diem'=>9],
            ['id_bangdiem'=>6,'diem'=>8],
            ['id_bangdiem'=>6,'diem'=>7],
            ['id_bangdiem'=>7,'diem'=>9],
            ['id_bangdiem'=>7,'diem'=>8],
            ['id_bangdiem'=>7,'diem'=>7],
        ]);
        DB::table('he_so2')->insert([
            ['id_bangdiem'=>1,'diem'=>9],
            ['id_bangdiem'=>1,'diem'=>8.5],
            ['id_bangdiem'=>2,'diem'=>9],
            ['id_bangdiem'=>2,'diem'=>8.5],
            ['id_bangdiem'=>3,'diem'=>9],
            ['id_bangdiem'=>3,'diem'=>8.5],
            ['id_bangdiem'=>4,'diem'=>9],
            ['id_bangdiem'=>4,'diem'=>8.5],
            ['id_bangdiem'=>5,'diem'=>9],
            ['id_bangdiem'=>5,'diem'=>8.5],
            ['id_bangdiem'=>6,'diem'=>9],
            ['id_bangdiem'=>6,'diem'=>8.5],
            ['id_bangdiem'=>7,'diem'=>9],
            ['id_bangdiem'=>7,'diem'=>8.5],
        ]);
        DB::table('he_so3')->insert([
            ['id_bangdiem'=>1,'diem'=>9],
            ['id_bangdiem'=>2,'diem'=>9],
            ['id_bangdiem'=>3,'diem'=>9],
            ['id_bangdiem'=>4,'diem'=>9],
            ['id_bangdiem'=>5,'diem'=>9],
            ['id_bangdiem'=>6,'diem'=>9],
            ['id_bangdiem'=>7,'diem'=>9],
        ]);
        DB::table('bang_diemc1')->insert([
            ['id_hocsinh'=>7,'id_giaovien'=>2,'id_mon'=>14],
            ['id_hocsinh'=>7,'id_giaovien'=>12,'id_mon'=>1],
            ['id_hocsinh'=>7,'id_giaovien'=>13,'id_mon'=>9],
            ['id_hocsinh'=>7,'id_giaovien'=>14,'id_mon'=>12],
            ['id_hocsinh'=>7,'id_giaovien'=>15,'id_mon'=>13],
            ['id_hocsinh'=>7,'id_giaovien'=>16,'id_mon'=>15],
            ['id_hocsinh'=>7,'id_giaovien'=>17,'id_mon'=>16],
            ['id_hocsinh'=>7,'id_giaovien'=>18,'id_mon'=>17],
            ['id_hocsinh'=>7,'id_giaovien'=>19,'id_mon'=>18],
        ]);
        DB::table('giua_ki_c1')->insert([
            ['id_bangdiemc1'=>1,'muc_do'=>'H','nhan_xet'=>"Bài viết còn mắc nhiều lỗi, cần rèn luyện nhiều hơn."],
            ['id_bangdiemc1'=>2,'muc_do'=>'H','nhan_xet'=>"Hiểu bài và hoàn thành tốt các bài học ."],
            ['id_bangdiemc1'=>3,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>4,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>5,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>6,'muc_do'=>'T','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>7,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>8,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>9,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
        ]);
        DB::table('cuoi_ki_c1')->insert([
            ['id_bangdiemc1'=>1,'muc_do'=>'H','diem'=>8,'nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>2,'muc_do'=>'H','diem'=>7,'nhan_xet'=>"Hiểu bài và hoàn thành tốt các bài học."],
            ['id_bangdiemc1'=>6,'muc_do'=>'T','diem'=>9,'nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
        ]);
        DB::table('cuoi_ki_c1')->insert([
            ['id_bangdiemc1'=>3,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>4,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>5,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>7,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>8,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
            ['id_bangdiemc1'=>9,'muc_do'=>'H','nhan_xet'=>"Nắm được kiến thức, kỹ năng cơ bản của môn học"],
        ]);
        DB::table('nang_luc')->insert([
            ['id_hocsinh'=>7,'id_giaovien'=>2,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>12,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>13,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>14,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>15,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>16,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>17,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>18,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
            ['id_hocsinh'=>7,'id_giaovien'=>19,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','nhan_xet'=>"Khả năng tự học cần có sự giúp đỡ của người khác."],
        ]);
        DB::table('pham_chat')->insert([
            ['id_hocsinh'=>7,'id_giaovien'=>2,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>12,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>13,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>14,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>15,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>16,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>17,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>18,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
            ['id_hocsinh'=>7,'id_giaovien'=>19,'muc_do1'=>'Đ','muc_do2'=>'Đ','muc_do3'=>'Đ','muc_do4'=>'Đ','nhan_xet'=>"Chưa có ý thức tự giác trong học tập."],
        ]);

        DB::table('thu_bao')->insert([
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
            ['tieu_de'=>"Kế hoạch năm hoc",'tom_tat'=>"Thông báo kế hoạch năm học 2018-2019 ",'noi_dung'=>"Theo kế hoạch thời gian năm học này, ngày tựu trường của tất cả các cấp học, ngành học sớm nhất vào ngày 01/8/2018, muộn nhất ngày 24/8/2018. Thống nhất toàn thành phố tổ chức khai giảng vào ngày 05/9/2018.
                Kết thúc học kỳ I trước ngày 20/01/2019; kết thúc năm học trước ngày 31/5/2019. Xét công nhận hoàn thành chương trình tiểu học và xét công nhận tốt nghiệp THCS trước ngày 15/6/2019. Hoàn thành tuyển sinh lóp 10 trước ngày 31/7/2019. ",
                'id_vanthu'=>1,'id_truong'=>2],
        ]);
    }
}
